### ISSUE TITLE
`No Shell Running` Exception when launching Gnome Tweak Tool (in WSL)

### ISSUE THREAD

**Issue by Melvin-Abraham** [nzjrs/gnome-tweak-tool#10]
I'm using WSL with Ubuntu 18.04 installed. Since I'm interested in opening GUI in WSL, I installed `XMing Server` in my Windows Machine and set variable `DISPLAY` accordingly in my Ubuntu WSL. All the GUI applications launch as expected without any issues. Later, to change the shell theme, I installed `gnome-shell` along with `gnome-tweaks`. But as and when I launch `gnome-tweaks`, I get the following exception:

```
melvin@xyz:~$ gnome-tweaks
WARNING : Shell not installed or running
WARNING : Shell not running
NoneType: None
WARNING : Error detecting shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 216, in __init__
    raise Exception("Shell not running or DBus service not available")
Exception: Shell not running or DBus service not available
```

Even my `DBus` service is working:

```
melvin@xyz:~$ ps -ef | grep dbus | grep -v grep
melvin      28     1  0 22:56 tty1     00:00:00 dbus-launch --autolaunch=ded84489a5cc43069ac8dbfa9f36e4f1 --binary-syntax --close-stderr
melvin      29     1  0 22:56 ?        00:00:00 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 5 --print-address 7 --session
```

The other issue is that it does not cause any changes in the shell (may it be fonts, themes, etc.) even after making changes. I tried terminating `WSL` and starting it again but still, no changes are reflected even though it remembers my previous settings. Please, let me know if there is any way to fix this...

**Comment by robertoalvesneto** [comment]
I have same problemn on wsl2, but i don't think that's the fault of the tweaks

**Comment by rfgamaral** [comment]
Same for me, but I'm running WSL2 with WSLg:

```
❯ gnome-tweaks                
WARNING : Shell not installed or running
WARNING : Shell not running
NoneType: None
WARNING : Error detecting shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 217, in __init__
    raise Exception("Shell not running or DBus service not available")
Exception: Shell not running or DBus service not available
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtweak/app.py", line 30, in do_activate
    self.win = Window(self, model)
  File "/usr/lib/python3/dist-packages/gtweak/tweakview.py", line 58, in __init__
    self._model.load_tweaks(self)
  File "/usr/lib/python3/dist-packages/gtweak/tweakmodel.py", line 107, in load_tweaks
    mods = __import__("gtweak.tweaks", globals(), locals(), tweak_files, 0)
  File "/usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_general.py", line 55, in <module>
    IgnoreLidSwitchTweak(),
  File "/usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_general.py", line 28, in __init__
    GetterSetterSwitchTweak.__init__(self, _("Suspend when laptop lid is closed"), **options)
  File "/usr/lib/python3/dist-packages/gtweak/widgets.py", line 469, in __init__
    sw.set_active(self.get_active())
  File "/usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_general.py", line 31, in get_active
    return not self._sync_inhibitor()
  File "/usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_general.py", line 42, in _sync_inhibitor
    bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
gi.repository.GLib.Error: g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=865dc9ce192c498a99c97b7587ab241f --binary-syntax --close-stderr”: Child process exited with code 1 (1)
```

Wondering if anyone has a solution for this?
